### ISSUE TITLE
Lógica proposiciónal

### ISSUE THREAD

**Issue by LuisAlexisMorales** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-LuisAlexisMorales#1]
[logica-luis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-LuisAlexisMorales/files/13185124/logica-luis.pdf)

**Comment by Maritza2893** [comment]
portada: 25%
Procedimientos: 20%
Figuras: 22%
resultados: 20%
total: 17.4%

**Comment by Maritza2893** [comment]
portada: 25%
procedimiento: 20%
figuras:22%
resultados:20%
total: 17.4%
Calificado por Maritza y Anais

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
